import type { Locale } from "@/i18n-config";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "../globals.css";

const beVietnamPro = Be_Vietnam_Pro({
	variable: "--font-be-vietnam-pro",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
  preload: true,
  fallback: ["sans-serif"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ lang: Locale }>;
}>) {
	const { lang } = await params;

	return (
		<html lang={lang}>
			<body
				className={`${beVietnamPro.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
