blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/bPjw9Xvabq
    about: For questions and support requests, please visit our Discord server.
  - name: Facebook
    url: https://www.facebook.com/xirothedev
    about: For collab and contact, please send a message in my facebook